apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveller-deployment
  labels:
    app: traveller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traveller
  template:
    metadata:
      labels:
        app: traveller
    spec:
      containers:
      - name: traveller
        image: darkmane/traveller:0.0.1
        env:
        - name: RNG_SEED
          value: override
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8080